name: "新功能提案"
description: "对已有功能的大幅度修改，或增添新的模组"
labels: ["B: 新功能 : |"]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "在提交issue之前，请检查以下三项内容："
    options:
    - label: "**我确认增加的内容不会在地图上生成新的结构** 由于服务器地图已经预生成完毕，因此不会同意会增加新建筑/矿物/植物的提案"
      required: true
    - label: "**我确认增加的内容不会影响游戏平衡** 例如等价交换、加速火把等Mod不符合服务器宗旨，因此不会添加"
      required: true
    - label: "我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一提案未被提交过。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 内容
    description: "要修改的内容或打算添加的Mod，并说明原因"
    placeholder: "例如:我想加一个 汤姆的简易存储(Tom's Simple Storage Mod)，这个模组可以方便玩家存储整理物品，统一管理"
  validations:
    required: true
